info:
    app-name: Employee Management
management:
    endpoint:
        health:
            show-details: ALWAYS
    endpoints:
        web:
            exposure:
                include: '[health, info, prometheus]'
server:
    error:
        include-binding-errors: ALWAYS
        include-message: ALWAYS
        include-stacktrace: ON_PARAM
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://babar.db.elephantsql.com:5432/asfjtcdi
        username: asfjtcdi
        password: m5WzMP3nfg8Gi_4pxoAyFjgNCm8F2Vo5
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    main:
        banner-mode: false
