
spring:
  datasource:
    url: $(DB_URL)
    username: $(DB_USERNAME)
    password: $(DB_PASSWORD)
  main:
    banner-mode: OFF
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  error:
    include-stacktrace: ON_PARAM
    include-message: ALWAYS
    include-binding-errors: ALWAYS
  port: 8080

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

info:
  app-name: Spring MasterClass